version: "3"
services:
  gitbook:
    build:
      context: .
    container_name: gitbook
    hostname: gitbook
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./book:/gitbook
      - ./polyfills.js:/usr/local/lib/node_modules/gitbook-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js
    command: >
      bash -c
      "
      if [ ! -f SUMMARY.md ]; then gitbook init; fi &&
      gitbook install &&
      gitbook serve
      "
    init: true
